### ISSUE TITLE
Headful Mode Broken For 4.1.2 AIs

### ISSUE THREAD

**Issue by NiteKat** [Bytekeeper/BWAIShotgun#4]
Launching Headful mode for a 4.1.2 AI stalls at the main menu.

**Comment by Bytekeeper** [comment]
4.1.2 and below use the registry to look for the Starcraft installation to load `bwapi.ini`.
This will require either:
* Overwriting "LoadRegString" (as bwheadless does)
* Changing the registry key (not nice)
* Patching BWAPI 4.1.2 to support env, like the newer versions (a lot of work, because what about 3.7.x?)
